// アプリ独自のコマンド (lib.rs の `generate_handler!`) をすべてここに並べる。
//
// 一覧 (app manifest) を宣言すると、Tauri はアプリ独自のコマンドにも ACL を適用し、
// `capabilities/*.json` で許可したウインドウからしか呼べなくなる。宣言しないと
// ローカルのページ (tauri://localhost) の全ウインドウから無条件に呼べてしまい、
// 窓ごとに capability を分けていても絞れているのはプラグインのコマンドだけになる。
//
// コマンドごとに `allow-<kebab-case>` / `deny-<kebab-case>` の permission が自動生成される
// (`permissions/autogenerated/`)。コマンドを足したら、ここと、それを invoke するページの
// capability の両方に足すこと。ここに無いコマンドはどの窓からも呼べない。
// 両者の一致は `src/lib.rs` のテスト (build.rs 側) と `tests/capabilities.test.mts`
// (capability 側) が検査する。
const APP_COMMANDS: &[&str] = &[
    "config_get_all",
    "config_set",
    "run_shell_command",
    "open_shell_log",
    "open_shell_log_dir",
    "sync_menu_bar",
    "open_preferences",
    "third_party_notices",
    "open_third_party_licenses",
    "take_screenshot_interactive",
    "take_screenshot_timer",
    "write_image_to_file",
    "load_image_file",
    "open_save_directory",
    "get_default_save_directory",
    "save_pasted_image",
    "ocr_image",
    "ocr_capture_region",
    "show_notification",
    "open_region_selector",
    "cancel_region_selection",
    "release_region_selector_for_countdown",
    "broadcast_region_selecting",
    "list_capture_windows",
    "start_video_recording",
    "stop_video_recording",
    "export_video",
    "check_ffmpeg_available",
    "capture_region_preview",
    "capture_region_ready",
    "capture_region_finish",
    "list_saved_images",
    "saved_image_thumbnail",
];

fn main() {
    tauri_build::try_build(
        tauri_build::Attributes::new()
            .app_manifest(tauri_build::AppManifest::new().commands(APP_COMMANDS)),
    )
    .expect("failed to run tauri-build");
}
