#!/usr/bin/env bash
# 配布物に含まれる依存ライブラリのライセンスを THIRD-PARTY-NOTICES.txt に書き出す。
# `pnpm notices` から呼ばれる。依存を足したり上げたりしたら流し直してコミットする
# (src-tauri/src/licenses.rs のテストが、直接依存がこのファイルに載っているかを見る)。
#
# Rust 側は cargo-about (`cargo install cargo-about --locked --features cli`)、
# 設定は src-tauri/about.toml、書式は src-tauri/about.hbs。
# npm 側は package.json の dependencies と、下の BUNDLED_RUNTIME を node_modules から読む。
# devDependencies は基本的に配布物に入らないが、BUNDLED_RUNTIME に挙げたものは
# vite がフロントの bundle に取り込む (2026-09 に vite build の client bundle に入る
# モジュールを調べて決めた):
#   - svelte / @sveltejs/kit: ランタイム (devDependencies にあるが、client bundle に入る)
#   - esm-env: svelte と @sveltejs/kit が import する推移依存
#   - tailwindcss: 生成 CSS に preflight と "tailwindcss v4 | MIT License" のバナーが入る
set -euo pipefail

cd "$(dirname "$0")/.."

OUT="THIRD-PARTY-NOTICES.txt"

if ! cargo about --version >/dev/null 2>&1; then
  echo "Error: cargo-about is not installed. Run: cargo install cargo-about --locked --features cli" >&2
  exit 1
fi
if [ ! -d node_modules ]; then
  echo "Error: node_modules is missing. Run: pnpm install" >&2
  exit 1
fi

# 同じディレクトリに作る。別ファイルシステムの /tmp からの mv はコピーになり、途中で
# 止まると壊れた出力が残る
TMP=$(mktemp "${OUT}.XXXXXX")
trap 'rm -f "$TMP"' EXIT

{
  cat <<'HEADER'
THIRD-PARTY NOTICES

FlashCap bundles the open source libraries listed below. Each entry gives the
license, the packages it applies to, and the license text as shipped by the
package. Generated by scripts/generate-third-party-notices.sh; do not edit by hand.

################################################################################
# JavaScript packages (bundled into the web view)
################################################################################

HEADER

  node - <<'NODE'
const fs = require("fs");
const path = require("path");

// devDependencies / 推移依存のうち、vite が bundle に取り込むもの。[名前, 探し始める package]。
// pnpm は推移依存を直下の node_modules に置かないので、依存元の隣から探す
const BUNDLED_RUNTIME = [
  ["svelte", null],
  ["@sveltejs/kit", null],
  ["tailwindcss", null],
  ["esm-env", "svelte"],
];

// package.json に license も repository も書いていない package。表記は同じリポジトリの
// Rust crate (tauri-plugin-drag、"Apache-2.0 OR MIT") に合わせる
const MISSING_METADATA = {
  "@crabnebula/tauri-plugin-drag": {
    license: "Apache-2.0 OR MIT",
    repository: "https://github.com/crabnebula-dev/drag-rs",
    note:
      "The package declares no license and ships no license text. It is published from\n" +
      "the repository above together with the tauri-plugin-drag Rust crate, which is\n" +
      "licensed Apache-2.0 OR MIT; see that crate in the Rust section below.",
  },
};

function packageDir(name, from) {
  if (!from) return path.join("node_modules", name);
  // node_modules/.pnpm/<pkg>@<ver>/node_modules/<from> の隣に推移依存が並ぶ
  const parent = fs.realpathSync(path.join("node_modules", from));
  const scopeDepth = from.startsWith("@") ? 2 : 1;
  let root = parent;
  for (let i = 0; i < scopeDepth; i++) root = path.dirname(root);
  return path.join(root, name);
}

const deps = Object.keys(JSON.parse(fs.readFileSync("package.json", "utf8")).dependencies);
const entries = deps.map((name) => [name, null]).concat(BUNDLED_RUNTIME);
entries.sort((a, b) => (a[0] < b[0] ? -1 : a[0] > b[0] ? 1 : 0));
for (const [name, from] of entries) {
  const dir = packageDir(name, from);
  const pkg = JSON.parse(fs.readFileSync(path.join(dir, "package.json"), "utf8"));
  const fallback = MISSING_METADATA[name] || {};
  const license = pkg.license || fallback.license;
  const repo =
    (typeof pkg.repository === "string" ? pkg.repository : pkg.repository?.url) || fallback.repository;
  if (!license) {
    throw new Error(`${name} declares no license; add it to MISSING_METADATA after checking by hand`);
  }
  // LICENSE.spdx のような SPDX のメタデータは本文ではないので除く
  const files = fs
    .readdirSync(dir)
    .filter((f) => /^(LICEN[CS]E|COPYING|NOTICE)/i.test(f) && !/\.spdx$/i.test(f))
    .sort();
  console.log("=".repeat(80));
  console.log(`License: ${license}`);
  console.log("");
  console.log("Used by:");
  console.log(`  ${name} ${pkg.version}${repo ? ` (${repo})` : ""}`);
  console.log("");
  if (files.length === 0) {
    // 本文が同梱されていない package。表記と配布元だけ残す
    console.log(fallback.note || "The package does not ship its license text; see the repository above.");
    console.log("");
    continue;
  }
  for (const f of files) {
    if (files.length > 1) console.log(`--- ${f} ---`);
    console.log(fs.readFileSync(path.join(dir, f), "utf8").replace(/\s+$/, ""));
    console.log("");
  }
}
NODE

  cat <<'HEADER'
################################################################################
# Rust crates (compiled into the binary)
################################################################################

HEADER

  # --fail: ライセンスを特定できない crate があれば警告で省略せず失敗させる
  cargo about generate --manifest-path src-tauri/Cargo.toml --locked --fail src-tauri/about.hbs
} > "$TMP"

mv "$TMP" "$OUT"
echo "Wrote $OUT ($(wc -l < "$OUT" | tr -d ' ') lines)"
